server:
  port: 7900
spring:
  jpa:
    generate-ddl: false #启动的时候是否自动生成dll语句
    show-sql: true
    hibernate:
      ddl-auto: none #jpa是依赖hibernate的，这里对hibernate也做配置，意思是启动的时候不做ddl语句的处理
  datasource:
    platform: h2
    schema: #这个可以不用配置，默认就是classpath:schema.sql
      - classpath:schema.sql
    data: #这个上同
      - classpath:data.sql
logging:
  level:
    root: info
    #显示SQL语句，同时把参数打印出来，跟showsql有一定联系的。
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.tigerjoys: DEBUG