spring:
  application:
    name: microservice-getway-zuul-reg-exp
server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka #将eureka注册到哪个server上
  instance:
    prefer-ip-address: true
