server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 20 #心跳的周期，默认30秒
    lease-expiration-duration-in-seconds: 90 #租期到期时间
# 监控多个微服物的配置1
#turbine:
#  aggregator:
#    clusterConfig: MICROSERVICE-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX,MICROSERVICE-CONSUMER-MOVIE-FEIGN-WITH-HYSTRIX
#  app-config: microservice-consumer-movie-ribbon-with-hystrix,microservice-consumer-movie-feign-with-hystrix
# 监控多个微服物的配置2
turbine:
  aggregator:
    clusterConfig: default
  app-config: microservice-consumer-movie-ribbon-with-hystrix,microservice-consumer-movie-feign-with-hystrix
  clusterNameExpression: "'default'"
