spring:
  application:
    name: microservice-getway-zuul
server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka #将eureka注册到哪个server上
  instance:
    prefer-ip-address: true
management: 
  security:
    enabled: false #关闭actuator验证，关闭一些特殊的url的验证请求，直接开放url

