spring:
  application:
    name: microservice-file-upload
  http:
    multipart:
      max-file-size: 2000Mb #单文件的大小，默认1M
      max-request-size: 2500Mb #总文件大小，默认10M
server:
  port: 8050
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka #将eureka注册到哪个server上
  instance:
    prefer-ip-address: true
#zuul:
#  sensitiveHeaders: #过滤掉一些头信息不要传递到上游服务中去
