security:
  basic:
    enabled: true
  user:
    name: user
    password: password
server:
  port: 8761
eureka:
  datacenter: cloud
  environment: product
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false #不要将自己当成eureka client，只把自己当成是eureka server
    fetch-registry: false #上同 单机模式下关闭
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka #将eureka注册到哪个server上
