spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix
server:
  port: 7901
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
management:
  security:
    enabled: false #关闭actuator验证
feign:
  hystrix:
    enabled: true #Edgware.SR3版本是默认关闭的，在以前的版本默认是开启的。