#如果要配置用户名和密码登录eureka，使用此写法，并且要在pom.xml中添加spring-boot-starter-security依赖
security:
  basic:
    enabled: true
  user:
    name: user
    password: password
server:
  port: 8761
eureka:
  #配置eureka dashboard 左上角的 System Status 显示的内容
  datacenter: cloud
  environment: product
  #如何解决Eureka Server 不踢出已关停的节点的问题？
  #server:
  #  enable-self-preservation: false #关闭自我保护机制
  #  eviction-interval-timer-in-ms: 60000 #清理间隔(单位毫秒，默认是60*1000)
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false #不要将自己当成eureka client，只把自己当成是eureka server
    fetch-registry: false #上同 单机模式下关闭
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka #将eureka注册到哪个server上
  #dashboard:
  #  enabled: true #禁用eureka首页，这样就访问不到管理界面了
  #  path: /x