#默认启动的时候在eureka控制台显示的是这样子的
#UNKNOWN  n/a (1) (1) UP (1) - DESKTOP-9CKN135:7900
#1.问题 将DESKTOP-9CKN135的链接地址换成IP 配置eureka.instance.prefer-ip-address=true
#想更改显示名称则配置 eureka.instance.instance-id:${spring.application.name}:${spring.application.instance_id:${server.port}}
#2.问题 UNKNOWN如何显示名称 只需要配置spring.application.name 即可
server:
  port: 7900
spring:
  jpa:
    generate-ddl: false #启动的时候是否自动生成dll语句
    show-sql: true
    hibernate:
      ddl-auto: none #jpa是依赖hibernate的，这里对hibernate也做配置，意思是启动的时候不做ddl语句的处理
  datasource:
    platform: h2
    schema: #这个可以不用配置，默认就是classpath:schema.sql
      - classpath:schema.sql
    data: #这个上同
      - classpath:data.sql
  application:
    name: microservice-provider-user #建议使用小写
logging:
  level:
    root: info
    #显示SQL语句，同时把参数打印出来，跟showsql有一定联系的。
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.tigerjoys: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
      #高可用的eureka的话，此项目注册到peer1中后，会同步到peer2,peer3，但是生成环境的话，建议多配置几个eureka
      #因为防止注册peer1的时候，peer1挂了，你连注册的机会都没了。
      #http://peer1:8761/eureka,http://peer2:8762/eureka,http://peer3:8763/eureka
      #defaultZone: http://peer1:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    #eureka metadata 可以自定义，启动了eureka服务后，将此项目启动，就可以在http://localhost:8761/eureka/apps/microservice-provider-user/ 下面找到配置的信息
    metadata-map:
      zone: ABC #这个是eureka可以识别的参数
      jack-chan: CNN #这个是我自定义的参数，不会影响客户端行为
    lease-renewal-interval-in-seconds: 20 #心跳的周期，默认30秒
    appname: USER-SERVICE-HAHA #配置在eureka注册的名称，即eureka dashboard 中 Application显示的名称
    #hostname: user 此功能是向eureka server注册的服务地址名称
management:
  security:
    enabled: false #关闭actuator验证